server:
  port: 2011

spring:
  application:
    name: configserver
  profiles:
    active: git #设置使用本地配置(默认是git,可以设置：subversion(SVN)，native(本地))
  cloud:
    config:
      server:
        #如下是GIT配置
        git:
          uri: https://github.com/chendy1109/ahz-config     # 配置git仓库的地址（最后不需要带/，否则会出现：No custom http config found for URL: XXX）
          search-paths: configs                             # git仓库地址下的相对搜索地址（可用使用通配符），可以配置多个，用,分割。可以{application}实现按应用查配置
          username: chendy1109                                            # git仓库的账号（公开仓库无需账号信息）
          password: D@yi0616                                            # git仓库的密码（公开仓库无需账号信息）
          default-label: main                             #git默认分支

        #如下是SVN配置
        #        svn:
        #          uri: http://svnhost:port/svn/app-config #SVN仓库地址
        #          username: svnuser #SVN账号(如果没有权限可为空)
        #          password: svnpassword #SVN密码(如果没有权限可为空)
        #          default-label: trunk #默认SVN分支

        #如下是本地文件配置
  #       native:
  #         search-locations: classpath:/configs #配置文件存放的目录
